export const projects = [
  {
    id: 1,
    title: "Simplest Way to Lower Blood Pressure",
    category: "video",
    description: "Rosemary for high blood pressure - natural remedies explained",
    youtubeUrl: "https://youtu.be/ftmU2okxjRk?si=KlB5T9odSO4U-szy",
    youtubeId: "ftmU2okxjRk",
  },
  {
    id: 2,
    title: "Top 10 Health Benefits of Nettle Tea",
    category: "video",
    description: "Discover the amazing health benefits of stinging nettle tea",
    youtubeUrl: "https://www.youtube.com/watch?si=X-oy9cU2dCP0vptm&v=yJNRkAl5LoI&feature=youtu.be",
    youtubeId: "yJNRkAl5LoI",
  },
  {
    id: 3,
    title: "AI Changing Everything",
    category: "video",
    description: "Exploring how artificial intelligence is transforming our world",
    youtubeUrl: "https://youtube.com/shorts/2glxLbgexkY?si=W171EPXRvKQBLEko",
    youtubeId: "2glxLbgexkY",
  },
  {
    id: 4,
    title: "The Way People Judge Your Work",
    category: "video",
    description: "Insights on how your work is perceived and evaluated",
    youtubeUrl: "https://www.youtube.com/shorts/9WFYVINUYcU?feature=share",
    youtubeId: "9WFYVINUYcU",
  },
  {
    id: 5,
    title: "Chasing for Shortcut",
    category: "video",
    description: "The pitfalls of seeking quick fixes and shortcuts",
    youtubeUrl: "https://youtube.com/shorts/rPTiy7Hg-qM?si=3Fq7cIUFfg3zxkEv",
    youtubeId: "rPTiy7Hg-qM",
  },
  {
    id: 6,
    title: "Struggling to Get Clients",
    category: "video",
    description: "Insights on challenges and solutions for acquiring clients",
    youtubeUrl: "https://youtube.com/shorts/rRz6eX8qqGY?si=sVqm551cw366PQTn",
    youtubeId: "rRz6eX8qqGY",
  },
  {
    id: 7,
    title: "Abonal Technologies Ad",
    category: "video",
    description: "Promotional video for Abonal Technologies",
    youtubeUrl: "https://youtube.com/shorts/lpaYptfoJsY?si=L6IiowkaHP1AoOni",
    youtubeId: "lpaYptfoJsY",
  },
]

